apiVersion: v1
kind: Namespace
metadata:
  name:  dev #nombre del namespace CAMBIAR
---
apiVersion: apps/v1
kind: Deployment #Deployment
metadata:
  name:  nodedev #nombre del deployment
  namespace: dev #nombre del namespace CAMBIAR
  labels: # labels del peploy
    app: label-deployment #label match del servicio
spec: #replicaset
  replicas: 2 #numero de replicas
  selector: #selector del replicaset
    matchLabels:
      app: label-deployment #machea con el label del POD
  template: #POD
    metadata:
      labels: #labels del pod
        app: label-deployment
    spec: 
      containers:
      - image:  appminio:7 #imagen del pod
        imagePullPolicy: IfNotPresent
        name:  nodedev #nombre del pod
        resources:
          requests:
            cpu: "20m" #memoria minima
            memory: "55M"
          limits: #maximo
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: nodedev
  namespace: dev #nombre del namespace CAMBIAR
spec:
  selector:
    app: label-deployment #label match del servicio
  #type:  NodePort
  ports:
  - protocol: TCP
    port: 7071
    targetPort:  7071 #puerto del contenedor, si fuera una img hecha por mi seria el de expose

#---
#kind: Ingress
#apiVersion: extensions/v1beta1
#metadata:
  #annotations:
    #kubernetes.io/ingress.class: nginx
  #name: dev
#spec:
 # rules:
 # - host: dev.demo.itm.gt
  #  http:
   #   paths:
     # - backend:
         # serviceName: nodedev
         # servicePort: 7011
       # path: /